name: PyConf Hyderabad 2022 site CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build
        run: |
          mkdir build
          cp *.* build/

      - name: Deploy
        run: |
          git config --global user.email "contact@hydpy.org"
          git config --global user.name "GitHub Action"
          git clone https://github.com/HydPy/hydpy.github.io.git pyconf-websites
          cd pyconf-websites
          rm -rf 2022
          mkdir 2022
          cp ../build/* 2022/
          git add .
          git commit -m "Github Actions: pyconfhyd2022-${GITHUB_RUN_ID}"
          git remote add origin-pages https://${{ secrets.GITHUB_TOKEN  }}@github.com/HydPy/hydpy.github.io.git
          git push origin-pages master